require: rubocop-sketchup

inherit_from: https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/a6325affd7a3c20ac30b070789f88f06b3633778/sketchup-style.yml

AllCops:
  Exclude:
    # Don't check third party libraries.
    - 'src/*/vendor/**/*'
    
  # Should really be Ruby 2.2.4 for SketchUp 2017 but RuboCop has dropped that
  # option.
  TargetRubyVersion: 2.4
  SketchUp:
    TargetSketchUpVersion: 2017

# False positives for modules documented in one file but not another, e.g. the
# extension wrapper.
Style/Documentation:
  Enabled: false

# Double negation is a handy Ruby idiom to assure a value is a Boolean, as there
# is no to_bool/to_boolean/to_b method. What the cop suggest, !var.nil?, doesn't
# even cater for Boolean false as input.
Style/DoubleNegation:
  Enabled: false

# .nil? doesn't read better than == nil.
Style/NilComparison:
  Enabled: false

# .zero? doesn't read better than == 0.
Style/NumericPredicate:
  Enabled: false

# Not available in SketchUp 2017 and 2018 (Ruby 2.2.4).
Style/SafeNavigation:
  Enabled: false

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# rubocop-sketchup

# Enable all SketchUp cops.
SketchupDeprecations:
  Enabled: true
SketchupPerformance:
  Enabled: true
SketchupRequirements:
  Enabled: true
SketchupSuggestions:
  Enabled: true
SketchupBugs:
  Enabled: true
  
# This is an extension made by the SketchUp team.
# For third party extensions, do not disable this cop.
SketchupRequirements/ShippedExtensionsNamespace:
  Enabled: false

# TODO: Move to sketchup-style.yml.
#
# SketchUp Tool interface and observer interfaces don't follow Ruby naming
# conventions.
Naming/MethodName:
  IgnoredPatterns:
    # Tool
    - '^\s*enableVCB\?(\(.*\))?$'
    - '^\s*getExtents(\(.*\))?$'
    - '^\s*getInstructorContentDirectory(\(.*\))?$'
    - '^\s*getMenu(\(.*\))?$'
    - '^\s*onCancel(\(.*\))?$'
    - '^\s*onKeyDown(\(.*\))?$'
    - '^\s*onKeyUp(\(.*\))?$'
    - '^\s*onLButtonDoubleClick(\(.*\))?$'
    - '^\s*onLButtonDown(\(.*\))?$'
    - '^\s*onLButtonUp(\(.*\))?$'
    - '^\s*onMButtonDoubleClick(\(.*\))?$'
    - '^\s*onMButtonDown(\(.*\))?$'
    - '^\s*onMButtonUp(\(.*\))?$'
    - '^\s*onMouseEnter(\(.*\))?$'
    - '^\s*onMouseLeave(\(.*\))?$'
    - '^\s*onMouseMove(\(.*\))?$'
    - '^\s*onMouseWheel(\(.*\))?$'
    - '^\s*onRButtonDown(\(.*\))?$'
    - '^\s*onRButtonUp(\(.*\))?$'
    - '^\s*onReturn(\(.*\))?$'
    - '^\s*onSetCursor(\(.*\))?$'
    - '^\s*onUserText(\(.*\))?$'
    # AppObserver
    - '^\s*expectsStartupModelNotifications(\(.*\))?$'
    - '^\s*onActivateModel(\(.*\))?$'
    - '^\s*onNewModel(\(.*\))?$'
    - '^\s*onOpenModel(\(.*\))?$'
    - '^\s*onQuit(\(.*\))?$'
    - '^\s*onUnloadExtension(\(.*\))?$'
    # DefinitionObserver
    - '^\s*onComponentInstanceAdded(\(.*\))?$'
    - '^\s*onComponentInstanceRemoved(\(.*\))?$'
    # DefinitionsObserver
    - '^\s*onComponentAdded(\(.*\))?$'
    - '^\s*onComponentPropertiesChanged(\(.*\))?$'
    - '^\s*onComponentRemoved(\(.*\))?$'
    - '^\s*onComponentTypeChanged(\(.*\))?$'
    # DimensionsObserver
    - '^\s*onTextChanged(\(.*\))?$'
    # EntitiesObserver
    - '^\s*onActiveSectionPlaneChanged(\(.*\))?$'
    - '^\s*onElementAdded(\(.*\))?$'
    - '^\s*onElementModified(\(.*\))?$'
    - '^\s*onElementRemoved(\(.*\))?$'
    - '^\s*onEraseEntities(\(.*\))?$'
    # EntityObserver
    - '^\s*onChangeEntity(\(.*\))?$'
    - '^\s*onEraseEntity(\(.*\))?$'
    # FrameChangeObserver
    - '^\s*frameChange(\(.*\))?$'
    # InstanceObserver
    - '^\s*onClose(\(.*\))?$'
    - '^\s*onOpen(\(.*\))?$'
    # LayersObserver
    - '^\s*onCurrentLayerChangedS(\(.*\))?$'
    - '^\s*onLayerAdded(\(.*\))?$'
    - '^\s*onLayerChanged(\(.*\))?$'
    - '^\s*onLayerRemoved(\(.*\))?$'
    - '^\s*onRemoveAllLayers(\(.*\))?$'
    # MaterialsObserver
    - '^\s*onMaterialAdd(\(.*\))?$'
    - '^\s*onMaterialChange(\(.*\))?$'
    - '^\s*onMaterialRefChange(\(.*\))?$'
    - '^\s*onMaterialRemove(\(.*\))?$'
    - '^\s*onMaterialSetCurrent(\(.*\))?$'
    - '^\s*onMaterialUndoRedo(\(.*\))?$'
    # ModelObserver
    - '^\s*onActivePathChanged(\(.*\))?$'
    - '^\s*onAfterComponentSaveAs(\(.*\))?$'
    - '^\s*onBeforeComponentSaveAs(\(.*\))?$'
    - '^\s*onDeleteModel(\(.*\))?$'
    - '^\s*onEraseAll(\(.*\))?$'
    - '^\s*onExplode(\(.*\))?$'
    - '^\s*onPidChanged(\(.*\))?$'
    - '^\s*onPlaceComponent(\(.*\))?$'
    - '^\s*onPostSaveModel(\(.*\))?$'
    - '^\s*onPreSaveModel(\(.*\))?$'
    - '^\s*onSaveModel(\(.*\))?$'
    - '^\s*onTransactionAbort(\(.*\))?$'
    - '^\s*onTransactionCommit(\(.*\))?$'
    - '^\s*onTransactionEmpty(\(.*\))?$'
    - '^\s*onTransactionRedo(\(.*\))?$'
    - '^\s*onTransactionStart(\(.*\))?$'
    - '^\s*onTransactionUndo(\(.*\))?$'
    # OptionsproviderObserver
    - '^\s*onOptionsProviderChanged(\(.*\))?$'
    # PagesObserver
    - '^\s*onContentsModified(\(.*\))?$'
    - '^\s*onElementAdded(\(.*\))?$'
    - '^\s*onElementRemoved(\(.*\))?$'
    # RenderingOptionsObserver
    - '^\s*onRenderingOptionsChanged(\(.*\))?$'
    # SelectionObserver
    - '^\s*onSelectionAdded(\(.*\))?$'
    - '^\s*onSelectionBulkChange(\(.*\))?$'
    - '^\s*onSelectionCleared(\(.*\))?$'
    - '^\s*onSelectionRemoved(\(.*\))?$'
    - '^\s*onSelectedRemoved(\(.*\))?$'
    # ShadowInfoObserver
    - '^\s*onShadowInfoChanged(\(.*\))?$'
    # ToolsObserver
    - '^\s*onActiveToolChanged(\(.*\))?$'
    - '^\s*onToolStateChanged(\(.*\))?$'
    # ViewObserver
    - '^\s*onViewChanged(\(.*\))?$'
